// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: raft_cmdpb.proto

package raft_cmdpb

import (
	errorpb "github.com/Aetherance/kv/proto/pkg/errorpb"
	metapb "github.com/Aetherance/kv/proto/pkg/metapb"
	raftpb "github.com/Aetherance/kv/proto/pkg/raftpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmdType int32

const (
	CmdType_Invalid CmdType = 0
	CmdType_Get     CmdType = 1
	CmdType_Put     CmdType = 3
	CmdType_Delete  CmdType = 4
	CmdType_Snap    CmdType = 5
)

// Enum value maps for CmdType.
var (
	CmdType_name = map[int32]string{
		0: "Invalid",
		1: "Get",
		3: "Put",
		4: "Delete",
		5: "Snap",
	}
	CmdType_value = map[string]int32{
		"Invalid": 0,
		"Get":     1,
		"Put":     3,
		"Delete":  4,
		"Snap":    5,
	}
)

func (x CmdType) Enum() *CmdType {
	p := new(CmdType)
	*p = x
	return p
}

func (x CmdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdType) Descriptor() protoreflect.EnumDescriptor {
	return file_raft_cmdpb_proto_enumTypes[0].Descriptor()
}

func (CmdType) Type() protoreflect.EnumType {
	return &file_raft_cmdpb_proto_enumTypes[0]
}

func (x CmdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdType.Descriptor instead.
func (CmdType) EnumDescriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{0}
}

type AdminCmdType int32

const (
	AdminCmdType_InvalidAdmin   AdminCmdType = 0
	AdminCmdType_ChangePeer     AdminCmdType = 1
	AdminCmdType_CompactLog     AdminCmdType = 3
	AdminCmdType_TransferLeader AdminCmdType = 4
	AdminCmdType_Split          AdminCmdType = 10
)

// Enum value maps for AdminCmdType.
var (
	AdminCmdType_name = map[int32]string{
		0:  "InvalidAdmin",
		1:  "ChangePeer",
		3:  "CompactLog",
		4:  "TransferLeader",
		10: "Split",
	}
	AdminCmdType_value = map[string]int32{
		"InvalidAdmin":   0,
		"ChangePeer":     1,
		"CompactLog":     3,
		"TransferLeader": 4,
		"Split":          10,
	}
)

func (x AdminCmdType) Enum() *AdminCmdType {
	p := new(AdminCmdType)
	*p = x
	return p
}

func (x AdminCmdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminCmdType) Descriptor() protoreflect.EnumDescriptor {
	return file_raft_cmdpb_proto_enumTypes[1].Descriptor()
}

func (AdminCmdType) Type() protoreflect.EnumType {
	return &file_raft_cmdpb_proto_enumTypes[1]
}

func (x AdminCmdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminCmdType.Descriptor instead.
func (AdminCmdType) EnumDescriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{1}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cf            string                 `protobuf:"bytes,1,opt,name=cf,proto3" json:"cf,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_raft_cmdpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_raft_cmdpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cf            string                 `protobuf:"bytes,1,opt,name=cf,proto3" json:"cf,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_raft_cmdpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_raft_cmdpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{3}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cf            string                 `protobuf:"bytes,1,opt,name=cf,proto3" json:"cf,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_raft_cmdpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_raft_cmdpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{5}
}

type SnapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapRequest) Reset() {
	*x = SnapRequest{}
	mi := &file_raft_cmdpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapRequest) ProtoMessage() {}

func (x *SnapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapRequest.ProtoReflect.Descriptor instead.
func (*SnapRequest) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{6}
}

type SnapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        *metapb.Region         `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapResponse) Reset() {
	*x = SnapResponse{}
	mi := &file_raft_cmdpb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapResponse) ProtoMessage() {}

func (x *SnapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapResponse.ProtoReflect.Descriptor instead.
func (*SnapResponse) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{7}
}

func (x *SnapResponse) GetRegion() *metapb.Region {
	if x != nil {
		return x.Region
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdType       CmdType                `protobuf:"varint,1,opt,name=cmd_type,json=cmdType,proto3,enum=raft_cmdpb.CmdType" json:"cmd_type,omitempty"`
	Get           *GetRequest            `protobuf:"bytes,2,opt,name=get,proto3" json:"get,omitempty"`
	Put           *PutRequest            `protobuf:"bytes,4,opt,name=put,proto3" json:"put,omitempty"`
	Delete        *DeleteRequest         `protobuf:"bytes,5,opt,name=delete,proto3" json:"delete,omitempty"`
	Snap          *SnapRequest           `protobuf:"bytes,6,opt,name=snap,proto3" json:"snap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_raft_cmdpb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{8}
}

func (x *Request) GetCmdType() CmdType {
	if x != nil {
		return x.CmdType
	}
	return CmdType_Invalid
}

func (x *Request) GetGet() *GetRequest {
	if x != nil {
		return x.Get
	}
	return nil
}

func (x *Request) GetPut() *PutRequest {
	if x != nil {
		return x.Put
	}
	return nil
}

func (x *Request) GetDelete() *DeleteRequest {
	if x != nil {
		return x.Delete
	}
	return nil
}

func (x *Request) GetSnap() *SnapRequest {
	if x != nil {
		return x.Snap
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdType       CmdType                `protobuf:"varint,1,opt,name=cmd_type,json=cmdType,proto3,enum=raft_cmdpb.CmdType" json:"cmd_type,omitempty"`
	Get           *GetResponse           `protobuf:"bytes,2,opt,name=get,proto3" json:"get,omitempty"`
	Put           *PutResponse           `protobuf:"bytes,4,opt,name=put,proto3" json:"put,omitempty"`
	Delete        *DeleteResponse        `protobuf:"bytes,5,opt,name=delete,proto3" json:"delete,omitempty"`
	Snap          *SnapResponse          `protobuf:"bytes,6,opt,name=snap,proto3" json:"snap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_raft_cmdpb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{9}
}

func (x *Response) GetCmdType() CmdType {
	if x != nil {
		return x.CmdType
	}
	return CmdType_Invalid
}

func (x *Response) GetGet() *GetResponse {
	if x != nil {
		return x.Get
	}
	return nil
}

func (x *Response) GetPut() *PutResponse {
	if x != nil {
		return x.Put
	}
	return nil
}

func (x *Response) GetDelete() *DeleteResponse {
	if x != nil {
		return x.Delete
	}
	return nil
}

func (x *Response) GetSnap() *SnapResponse {
	if x != nil {
		return x.Snap
	}
	return nil
}

type ChangePeerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This can be only called in internal Raftstore now.
	ChangeType    raftpb.ConfChangeType `protobuf:"varint,1,opt,name=change_type,json=changeType,proto3,enum=raftpb.ConfChangeType" json:"change_type,omitempty"`
	Peer          *metapb.Peer          `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePeerRequest) Reset() {
	*x = ChangePeerRequest{}
	mi := &file_raft_cmdpb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePeerRequest) ProtoMessage() {}

func (x *ChangePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePeerRequest.ProtoReflect.Descriptor instead.
func (*ChangePeerRequest) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{10}
}

func (x *ChangePeerRequest) GetChangeType() raftpb.ConfChangeType {
	if x != nil {
		return x.ChangeType
	}
	return raftpb.ConfChangeType(0)
}

func (x *ChangePeerRequest) GetPeer() *metapb.Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type ChangePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        *metapb.Region         `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePeerResponse) Reset() {
	*x = ChangePeerResponse{}
	mi := &file_raft_cmdpb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePeerResponse) ProtoMessage() {}

func (x *ChangePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePeerResponse.ProtoReflect.Descriptor instead.
func (*ChangePeerResponse) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{11}
}

func (x *ChangePeerResponse) GetRegion() *metapb.Region {
	if x != nil {
		return x.Region
	}
	return nil
}

type SplitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This can be only called in internal Raftstore now.
	// The split_key has to exist in the splitting region.
	SplitKey []byte `protobuf:"bytes,1,opt,name=split_key,json=splitKey,proto3" json:"split_key,omitempty"`
	// We split the region into two. The first uses the origin
	// parent region id, and the second uses the new_region_id.
	// We must guarantee that the new_region_id is global unique.
	NewRegionId uint64 `protobuf:"varint,2,opt,name=new_region_id,json=newRegionId,proto3" json:"new_region_id,omitempty"`
	// The peer ids for the new split region.
	NewPeerIds    []uint64 `protobuf:"varint,3,rep,packed,name=new_peer_ids,json=newPeerIds,proto3" json:"new_peer_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitRequest) Reset() {
	*x = SplitRequest{}
	mi := &file_raft_cmdpb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitRequest) ProtoMessage() {}

func (x *SplitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitRequest.ProtoReflect.Descriptor instead.
func (*SplitRequest) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{12}
}

func (x *SplitRequest) GetSplitKey() []byte {
	if x != nil {
		return x.SplitKey
	}
	return nil
}

func (x *SplitRequest) GetNewRegionId() uint64 {
	if x != nil {
		return x.NewRegionId
	}
	return 0
}

func (x *SplitRequest) GetNewPeerIds() []uint64 {
	if x != nil {
		return x.NewPeerIds
	}
	return nil
}

type SplitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SplitResponse contains the region where specific keys have split into.
	Regions       []*metapb.Region `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SplitResponse) Reset() {
	*x = SplitResponse{}
	mi := &file_raft_cmdpb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitResponse) ProtoMessage() {}

func (x *SplitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitResponse.ProtoReflect.Descriptor instead.
func (*SplitResponse) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{13}
}

func (x *SplitResponse) GetRegions() []*metapb.Region {
	if x != nil {
		return x.Regions
	}
	return nil
}

type CompactLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompactIndex  uint64                 `protobuf:"varint,1,opt,name=compact_index,json=compactIndex,proto3" json:"compact_index,omitempty"`
	CompactTerm   uint64                 `protobuf:"varint,2,opt,name=compact_term,json=compactTerm,proto3" json:"compact_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactLogRequest) Reset() {
	*x = CompactLogRequest{}
	mi := &file_raft_cmdpb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactLogRequest) ProtoMessage() {}

func (x *CompactLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactLogRequest.ProtoReflect.Descriptor instead.
func (*CompactLogRequest) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{14}
}

func (x *CompactLogRequest) GetCompactIndex() uint64 {
	if x != nil {
		return x.CompactIndex
	}
	return 0
}

func (x *CompactLogRequest) GetCompactTerm() uint64 {
	if x != nil {
		return x.CompactTerm
	}
	return 0
}

type CompactLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactLogResponse) Reset() {
	*x = CompactLogResponse{}
	mi := &file_raft_cmdpb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactLogResponse) ProtoMessage() {}

func (x *CompactLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactLogResponse.ProtoReflect.Descriptor instead.
func (*CompactLogResponse) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{15}
}

type TransferLeaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *metapb.Peer           `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferLeaderRequest) Reset() {
	*x = TransferLeaderRequest{}
	mi := &file_raft_cmdpb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferLeaderRequest) ProtoMessage() {}

func (x *TransferLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferLeaderRequest.ProtoReflect.Descriptor instead.
func (*TransferLeaderRequest) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{16}
}

func (x *TransferLeaderRequest) GetPeer() *metapb.Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type TransferLeaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferLeaderResponse) Reset() {
	*x = TransferLeaderResponse{}
	mi := &file_raft_cmdpb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferLeaderResponse) ProtoMessage() {}

func (x *TransferLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferLeaderResponse.ProtoReflect.Descriptor instead.
func (*TransferLeaderResponse) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{17}
}

type AdminRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CmdType        AdminCmdType           `protobuf:"varint,1,opt,name=cmd_type,json=cmdType,proto3,enum=raft_cmdpb.AdminCmdType" json:"cmd_type,omitempty"`
	ChangePeer     *ChangePeerRequest     `protobuf:"bytes,2,opt,name=change_peer,json=changePeer,proto3" json:"change_peer,omitempty"`
	CompactLog     *CompactLogRequest     `protobuf:"bytes,4,opt,name=compact_log,json=compactLog,proto3" json:"compact_log,omitempty"`
	TransferLeader *TransferLeaderRequest `protobuf:"bytes,5,opt,name=transfer_leader,json=transferLeader,proto3" json:"transfer_leader,omitempty"`
	Split          *SplitRequest          `protobuf:"bytes,10,opt,name=split,proto3" json:"split,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminRequest) Reset() {
	*x = AdminRequest{}
	mi := &file_raft_cmdpb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRequest) ProtoMessage() {}

func (x *AdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRequest.ProtoReflect.Descriptor instead.
func (*AdminRequest) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{18}
}

func (x *AdminRequest) GetCmdType() AdminCmdType {
	if x != nil {
		return x.CmdType
	}
	return AdminCmdType_InvalidAdmin
}

func (x *AdminRequest) GetChangePeer() *ChangePeerRequest {
	if x != nil {
		return x.ChangePeer
	}
	return nil
}

func (x *AdminRequest) GetCompactLog() *CompactLogRequest {
	if x != nil {
		return x.CompactLog
	}
	return nil
}

func (x *AdminRequest) GetTransferLeader() *TransferLeaderRequest {
	if x != nil {
		return x.TransferLeader
	}
	return nil
}

func (x *AdminRequest) GetSplit() *SplitRequest {
	if x != nil {
		return x.Split
	}
	return nil
}

type AdminResponse struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	CmdType        AdminCmdType            `protobuf:"varint,1,opt,name=cmd_type,json=cmdType,proto3,enum=raft_cmdpb.AdminCmdType" json:"cmd_type,omitempty"`
	ChangePeer     *ChangePeerResponse     `protobuf:"bytes,2,opt,name=change_peer,json=changePeer,proto3" json:"change_peer,omitempty"`
	CompactLog     *CompactLogResponse     `protobuf:"bytes,4,opt,name=compact_log,json=compactLog,proto3" json:"compact_log,omitempty"`
	TransferLeader *TransferLeaderResponse `protobuf:"bytes,5,opt,name=transfer_leader,json=transferLeader,proto3" json:"transfer_leader,omitempty"`
	Split          *SplitResponse          `protobuf:"bytes,10,opt,name=split,proto3" json:"split,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminResponse) Reset() {
	*x = AdminResponse{}
	mi := &file_raft_cmdpb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResponse) ProtoMessage() {}

func (x *AdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResponse.ProtoReflect.Descriptor instead.
func (*AdminResponse) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{19}
}

func (x *AdminResponse) GetCmdType() AdminCmdType {
	if x != nil {
		return x.CmdType
	}
	return AdminCmdType_InvalidAdmin
}

func (x *AdminResponse) GetChangePeer() *ChangePeerResponse {
	if x != nil {
		return x.ChangePeer
	}
	return nil
}

func (x *AdminResponse) GetCompactLog() *CompactLogResponse {
	if x != nil {
		return x.CompactLog
	}
	return nil
}

func (x *AdminResponse) GetTransferLeader() *TransferLeaderResponse {
	if x != nil {
		return x.TransferLeader
	}
	return nil
}

func (x *AdminResponse) GetSplit() *SplitResponse {
	if x != nil {
		return x.Split
	}
	return nil
}

type RaftRequestHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Peer          *metapb.Peer           `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	RegionEpoch   *metapb.RegionEpoch    `protobuf:"bytes,4,opt,name=region_epoch,json=regionEpoch,proto3" json:"region_epoch,omitempty"`
	Term          uint64                 `protobuf:"varint,5,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftRequestHeader) Reset() {
	*x = RaftRequestHeader{}
	mi := &file_raft_cmdpb_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftRequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftRequestHeader) ProtoMessage() {}

func (x *RaftRequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftRequestHeader.ProtoReflect.Descriptor instead.
func (*RaftRequestHeader) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{20}
}

func (x *RaftRequestHeader) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *RaftRequestHeader) GetPeer() *metapb.Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *RaftRequestHeader) GetRegionEpoch() *metapb.RegionEpoch {
	if x != nil {
		return x.RegionEpoch
	}
	return nil
}

func (x *RaftRequestHeader) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type RaftResponseHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *errorpb.Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Uuid          []byte                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	CurrentTerm   uint64                 `protobuf:"varint,3,opt,name=current_term,json=currentTerm,proto3" json:"current_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftResponseHeader) Reset() {
	*x = RaftResponseHeader{}
	mi := &file_raft_cmdpb_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftResponseHeader) ProtoMessage() {}

func (x *RaftResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftResponseHeader.ProtoReflect.Descriptor instead.
func (*RaftResponseHeader) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{21}
}

func (x *RaftResponseHeader) GetError() *errorpb.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RaftResponseHeader) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *RaftResponseHeader) GetCurrentTerm() uint64 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

type RaftCmdRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *RaftRequestHeader     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// We can't enclose normal requests and administrator request
	// at same time.
	Requests      []*Request    `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	AdminRequest  *AdminRequest `protobuf:"bytes,3,opt,name=admin_request,json=adminRequest,proto3" json:"admin_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftCmdRequest) Reset() {
	*x = RaftCmdRequest{}
	mi := &file_raft_cmdpb_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftCmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftCmdRequest) ProtoMessage() {}

func (x *RaftCmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftCmdRequest.ProtoReflect.Descriptor instead.
func (*RaftCmdRequest) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{22}
}

func (x *RaftCmdRequest) GetHeader() *RaftRequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RaftCmdRequest) GetRequests() []*Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *RaftCmdRequest) GetAdminRequest() *AdminRequest {
	if x != nil {
		return x.AdminRequest
	}
	return nil
}

type RaftCmdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *RaftResponseHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Responses     []*Response            `protobuf:"bytes,2,rep,name=responses,proto3" json:"responses,omitempty"`
	AdminResponse *AdminResponse         `protobuf:"bytes,3,opt,name=admin_response,json=adminResponse,proto3" json:"admin_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftCmdResponse) Reset() {
	*x = RaftCmdResponse{}
	mi := &file_raft_cmdpb_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftCmdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftCmdResponse) ProtoMessage() {}

func (x *RaftCmdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftCmdResponse.ProtoReflect.Descriptor instead.
func (*RaftCmdResponse) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{23}
}

func (x *RaftCmdResponse) GetHeader() *RaftResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RaftCmdResponse) GetResponses() []*Response {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *RaftCmdResponse) GetAdminResponse() *AdminResponse {
	if x != nil {
		return x.AdminResponse
	}
	return nil
}

var File_raft_cmdpb_proto protoreflect.FileDescriptor

const file_raft_cmdpb_proto_rawDesc = "" +
	"\n" +
	"\x10raft_cmdpb.proto\x12\n" +
	"raft_cmdpb\x1a\fmetapb.proto\x1a\rerrorpb.proto\x1a\fraftpb.proto\".\n" +
	"\n" +
	"GetRequest\x12\x0e\n" +
	"\x02cf\x18\x01 \x01(\tR\x02cf\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"D\n" +
	"\n" +
	"PutRequest\x12\x0e\n" +
	"\x02cf\x18\x01 \x01(\tR\x02cf\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"\r\n" +
	"\vPutResponse\"1\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02cf\x18\x01 \x01(\tR\x02cf\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"\x10\n" +
	"\x0eDeleteResponse\"\r\n" +
	"\vSnapRequest\"6\n" +
	"\fSnapResponse\x12&\n" +
	"\x06region\x18\x01 \x01(\v2\x0e.metapb.RegionR\x06region\"\xed\x01\n" +
	"\aRequest\x12.\n" +
	"\bcmd_type\x18\x01 \x01(\x0e2\x13.raft_cmdpb.CmdTypeR\acmdType\x12(\n" +
	"\x03get\x18\x02 \x01(\v2\x16.raft_cmdpb.GetRequestR\x03get\x12(\n" +
	"\x03put\x18\x04 \x01(\v2\x16.raft_cmdpb.PutRequestR\x03put\x121\n" +
	"\x06delete\x18\x05 \x01(\v2\x19.raft_cmdpb.DeleteRequestR\x06delete\x12+\n" +
	"\x04snap\x18\x06 \x01(\v2\x17.raft_cmdpb.SnapRequestR\x04snap\"\xf2\x01\n" +
	"\bResponse\x12.\n" +
	"\bcmd_type\x18\x01 \x01(\x0e2\x13.raft_cmdpb.CmdTypeR\acmdType\x12)\n" +
	"\x03get\x18\x02 \x01(\v2\x17.raft_cmdpb.GetResponseR\x03get\x12)\n" +
	"\x03put\x18\x04 \x01(\v2\x17.raft_cmdpb.PutResponseR\x03put\x122\n" +
	"\x06delete\x18\x05 \x01(\v2\x1a.raft_cmdpb.DeleteResponseR\x06delete\x12,\n" +
	"\x04snap\x18\x06 \x01(\v2\x18.raft_cmdpb.SnapResponseR\x04snap\"n\n" +
	"\x11ChangePeerRequest\x127\n" +
	"\vchange_type\x18\x01 \x01(\x0e2\x16.raftpb.ConfChangeTypeR\n" +
	"changeType\x12 \n" +
	"\x04peer\x18\x02 \x01(\v2\f.metapb.PeerR\x04peer\"<\n" +
	"\x12ChangePeerResponse\x12&\n" +
	"\x06region\x18\x01 \x01(\v2\x0e.metapb.RegionR\x06region\"q\n" +
	"\fSplitRequest\x12\x1b\n" +
	"\tsplit_key\x18\x01 \x01(\fR\bsplitKey\x12\"\n" +
	"\rnew_region_id\x18\x02 \x01(\x04R\vnewRegionId\x12 \n" +
	"\fnew_peer_ids\x18\x03 \x03(\x04R\n" +
	"newPeerIds\"9\n" +
	"\rSplitResponse\x12(\n" +
	"\aregions\x18\x01 \x03(\v2\x0e.metapb.RegionR\aregions\"[\n" +
	"\x11CompactLogRequest\x12#\n" +
	"\rcompact_index\x18\x01 \x01(\x04R\fcompactIndex\x12!\n" +
	"\fcompact_term\x18\x02 \x01(\x04R\vcompactTerm\"\x14\n" +
	"\x12CompactLogResponse\"9\n" +
	"\x15TransferLeaderRequest\x12 \n" +
	"\x04peer\x18\x01 \x01(\v2\f.metapb.PeerR\x04peer\"\x18\n" +
	"\x16TransferLeaderResponse\"\xbf\x02\n" +
	"\fAdminRequest\x123\n" +
	"\bcmd_type\x18\x01 \x01(\x0e2\x18.raft_cmdpb.AdminCmdTypeR\acmdType\x12>\n" +
	"\vchange_peer\x18\x02 \x01(\v2\x1d.raft_cmdpb.ChangePeerRequestR\n" +
	"changePeer\x12>\n" +
	"\vcompact_log\x18\x04 \x01(\v2\x1d.raft_cmdpb.CompactLogRequestR\n" +
	"compactLog\x12J\n" +
	"\x0ftransfer_leader\x18\x05 \x01(\v2!.raft_cmdpb.TransferLeaderRequestR\x0etransferLeader\x12.\n" +
	"\x05split\x18\n" +
	" \x01(\v2\x18.raft_cmdpb.SplitRequestR\x05split\"\xc4\x02\n" +
	"\rAdminResponse\x123\n" +
	"\bcmd_type\x18\x01 \x01(\x0e2\x18.raft_cmdpb.AdminCmdTypeR\acmdType\x12?\n" +
	"\vchange_peer\x18\x02 \x01(\v2\x1e.raft_cmdpb.ChangePeerResponseR\n" +
	"changePeer\x12?\n" +
	"\vcompact_log\x18\x04 \x01(\v2\x1e.raft_cmdpb.CompactLogResponseR\n" +
	"compactLog\x12K\n" +
	"\x0ftransfer_leader\x18\x05 \x01(\v2\".raft_cmdpb.TransferLeaderResponseR\x0etransferLeader\x12/\n" +
	"\x05split\x18\n" +
	" \x01(\v2\x19.raft_cmdpb.SplitResponseR\x05split\"\x9e\x01\n" +
	"\x11RaftRequestHeader\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x12 \n" +
	"\x04peer\x18\x02 \x01(\v2\f.metapb.PeerR\x04peer\x126\n" +
	"\fregion_epoch\x18\x04 \x01(\v2\x13.metapb.RegionEpochR\vregionEpoch\x12\x12\n" +
	"\x04term\x18\x05 \x01(\x04R\x04term\"q\n" +
	"\x12RaftResponseHeader\x12$\n" +
	"\x05error\x18\x01 \x01(\v2\x0e.errorpb.ErrorR\x05error\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\fR\x04uuid\x12!\n" +
	"\fcurrent_term\x18\x03 \x01(\x04R\vcurrentTerm\"\xb7\x01\n" +
	"\x0eRaftCmdRequest\x125\n" +
	"\x06header\x18\x01 \x01(\v2\x1d.raft_cmdpb.RaftRequestHeaderR\x06header\x12/\n" +
	"\brequests\x18\x02 \x03(\v2\x13.raft_cmdpb.RequestR\brequests\x12=\n" +
	"\radmin_request\x18\x03 \x01(\v2\x18.raft_cmdpb.AdminRequestR\fadminRequest\"\xbf\x01\n" +
	"\x0fRaftCmdResponse\x126\n" +
	"\x06header\x18\x01 \x01(\v2\x1e.raft_cmdpb.RaftResponseHeaderR\x06header\x122\n" +
	"\tresponses\x18\x02 \x03(\v2\x14.raft_cmdpb.ResponseR\tresponses\x12@\n" +
	"\x0eadmin_response\x18\x03 \x01(\v2\x19.raft_cmdpb.AdminResponseR\radminResponse*>\n" +
	"\aCmdType\x12\v\n" +
	"\aInvalid\x10\x00\x12\a\n" +
	"\x03Get\x10\x01\x12\a\n" +
	"\x03Put\x10\x03\x12\n" +
	"\n" +
	"\x06Delete\x10\x04\x12\b\n" +
	"\x04Snap\x10\x05*_\n" +
	"\fAdminCmdType\x12\x10\n" +
	"\fInvalidAdmin\x10\x00\x12\x0e\n" +
	"\n" +
	"ChangePeer\x10\x01\x12\x0e\n" +
	"\n" +
	"CompactLog\x10\x03\x12\x12\n" +
	"\x0eTransferLeader\x10\x04\x12\t\n" +
	"\x05Split\x10\n" +
	"B:Z8github.com/Aetherance/kv/proto/pkg/raft_cmdpb;raft_cmdpbb\x06proto3"

var (
	file_raft_cmdpb_proto_rawDescOnce sync.Once
	file_raft_cmdpb_proto_rawDescData []byte
)

func file_raft_cmdpb_proto_rawDescGZIP() []byte {
	file_raft_cmdpb_proto_rawDescOnce.Do(func() {
		file_raft_cmdpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raft_cmdpb_proto_rawDesc), len(file_raft_cmdpb_proto_rawDesc)))
	})
	return file_raft_cmdpb_proto_rawDescData
}

var file_raft_cmdpb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_raft_cmdpb_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_raft_cmdpb_proto_goTypes = []any{
	(CmdType)(0),                   // 0: raft_cmdpb.CmdType
	(AdminCmdType)(0),              // 1: raft_cmdpb.AdminCmdType
	(*GetRequest)(nil),             // 2: raft_cmdpb.GetRequest
	(*GetResponse)(nil),            // 3: raft_cmdpb.GetResponse
	(*PutRequest)(nil),             // 4: raft_cmdpb.PutRequest
	(*PutResponse)(nil),            // 5: raft_cmdpb.PutResponse
	(*DeleteRequest)(nil),          // 6: raft_cmdpb.DeleteRequest
	(*DeleteResponse)(nil),         // 7: raft_cmdpb.DeleteResponse
	(*SnapRequest)(nil),            // 8: raft_cmdpb.SnapRequest
	(*SnapResponse)(nil),           // 9: raft_cmdpb.SnapResponse
	(*Request)(nil),                // 10: raft_cmdpb.Request
	(*Response)(nil),               // 11: raft_cmdpb.Response
	(*ChangePeerRequest)(nil),      // 12: raft_cmdpb.ChangePeerRequest
	(*ChangePeerResponse)(nil),     // 13: raft_cmdpb.ChangePeerResponse
	(*SplitRequest)(nil),           // 14: raft_cmdpb.SplitRequest
	(*SplitResponse)(nil),          // 15: raft_cmdpb.SplitResponse
	(*CompactLogRequest)(nil),      // 16: raft_cmdpb.CompactLogRequest
	(*CompactLogResponse)(nil),     // 17: raft_cmdpb.CompactLogResponse
	(*TransferLeaderRequest)(nil),  // 18: raft_cmdpb.TransferLeaderRequest
	(*TransferLeaderResponse)(nil), // 19: raft_cmdpb.TransferLeaderResponse
	(*AdminRequest)(nil),           // 20: raft_cmdpb.AdminRequest
	(*AdminResponse)(nil),          // 21: raft_cmdpb.AdminResponse
	(*RaftRequestHeader)(nil),      // 22: raft_cmdpb.RaftRequestHeader
	(*RaftResponseHeader)(nil),     // 23: raft_cmdpb.RaftResponseHeader
	(*RaftCmdRequest)(nil),         // 24: raft_cmdpb.RaftCmdRequest
	(*RaftCmdResponse)(nil),        // 25: raft_cmdpb.RaftCmdResponse
	(*metapb.Region)(nil),          // 26: metapb.Region
	(raftpb.ConfChangeType)(0),     // 27: raftpb.ConfChangeType
	(*metapb.Peer)(nil),            // 28: metapb.Peer
	(*metapb.RegionEpoch)(nil),     // 29: metapb.RegionEpoch
	(*errorpb.Error)(nil),          // 30: errorpb.Error
}
var file_raft_cmdpb_proto_depIdxs = []int32{
	26, // 0: raft_cmdpb.SnapResponse.region:type_name -> metapb.Region
	0,  // 1: raft_cmdpb.Request.cmd_type:type_name -> raft_cmdpb.CmdType
	2,  // 2: raft_cmdpb.Request.get:type_name -> raft_cmdpb.GetRequest
	4,  // 3: raft_cmdpb.Request.put:type_name -> raft_cmdpb.PutRequest
	6,  // 4: raft_cmdpb.Request.delete:type_name -> raft_cmdpb.DeleteRequest
	8,  // 5: raft_cmdpb.Request.snap:type_name -> raft_cmdpb.SnapRequest
	0,  // 6: raft_cmdpb.Response.cmd_type:type_name -> raft_cmdpb.CmdType
	3,  // 7: raft_cmdpb.Response.get:type_name -> raft_cmdpb.GetResponse
	5,  // 8: raft_cmdpb.Response.put:type_name -> raft_cmdpb.PutResponse
	7,  // 9: raft_cmdpb.Response.delete:type_name -> raft_cmdpb.DeleteResponse
	9,  // 10: raft_cmdpb.Response.snap:type_name -> raft_cmdpb.SnapResponse
	27, // 11: raft_cmdpb.ChangePeerRequest.change_type:type_name -> raftpb.ConfChangeType
	28, // 12: raft_cmdpb.ChangePeerRequest.peer:type_name -> metapb.Peer
	26, // 13: raft_cmdpb.ChangePeerResponse.region:type_name -> metapb.Region
	26, // 14: raft_cmdpb.SplitResponse.regions:type_name -> metapb.Region
	28, // 15: raft_cmdpb.TransferLeaderRequest.peer:type_name -> metapb.Peer
	1,  // 16: raft_cmdpb.AdminRequest.cmd_type:type_name -> raft_cmdpb.AdminCmdType
	12, // 17: raft_cmdpb.AdminRequest.change_peer:type_name -> raft_cmdpb.ChangePeerRequest
	16, // 18: raft_cmdpb.AdminRequest.compact_log:type_name -> raft_cmdpb.CompactLogRequest
	18, // 19: raft_cmdpb.AdminRequest.transfer_leader:type_name -> raft_cmdpb.TransferLeaderRequest
	14, // 20: raft_cmdpb.AdminRequest.split:type_name -> raft_cmdpb.SplitRequest
	1,  // 21: raft_cmdpb.AdminResponse.cmd_type:type_name -> raft_cmdpb.AdminCmdType
	13, // 22: raft_cmdpb.AdminResponse.change_peer:type_name -> raft_cmdpb.ChangePeerResponse
	17, // 23: raft_cmdpb.AdminResponse.compact_log:type_name -> raft_cmdpb.CompactLogResponse
	19, // 24: raft_cmdpb.AdminResponse.transfer_leader:type_name -> raft_cmdpb.TransferLeaderResponse
	15, // 25: raft_cmdpb.AdminResponse.split:type_name -> raft_cmdpb.SplitResponse
	28, // 26: raft_cmdpb.RaftRequestHeader.peer:type_name -> metapb.Peer
	29, // 27: raft_cmdpb.RaftRequestHeader.region_epoch:type_name -> metapb.RegionEpoch
	30, // 28: raft_cmdpb.RaftResponseHeader.error:type_name -> errorpb.Error
	22, // 29: raft_cmdpb.RaftCmdRequest.header:type_name -> raft_cmdpb.RaftRequestHeader
	10, // 30: raft_cmdpb.RaftCmdRequest.requests:type_name -> raft_cmdpb.Request
	20, // 31: raft_cmdpb.RaftCmdRequest.admin_request:type_name -> raft_cmdpb.AdminRequest
	23, // 32: raft_cmdpb.RaftCmdResponse.header:type_name -> raft_cmdpb.RaftResponseHeader
	11, // 33: raft_cmdpb.RaftCmdResponse.responses:type_name -> raft_cmdpb.Response
	21, // 34: raft_cmdpb.RaftCmdResponse.admin_response:type_name -> raft_cmdpb.AdminResponse
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_raft_cmdpb_proto_init() }
func file_raft_cmdpb_proto_init() {
	if File_raft_cmdpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raft_cmdpb_proto_rawDesc), len(file_raft_cmdpb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_raft_cmdpb_proto_goTypes,
		DependencyIndexes: file_raft_cmdpb_proto_depIdxs,
		EnumInfos:         file_raft_cmdpb_proto_enumTypes,
		MessageInfos:      file_raft_cmdpb_proto_msgTypes,
	}.Build()
	File_raft_cmdpb_proto = out.File
	file_raft_cmdpb_proto_goTypes = nil
	file_raft_cmdpb_proto_depIdxs = nil
}
