// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: raft_cmdpb.proto

package raft_cmdpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CmdType int32

const (
	CmdType_Invalid     CmdType = 0
	CmdType_Put         CmdType = 3
	CmdType_Delete      CmdType = 4
	CmdType_ReadBarrier CmdType = 5
)

// Enum value maps for CmdType.
var (
	CmdType_name = map[int32]string{
		0: "Invalid",
		3: "Put",
		4: "Delete",
		5: "ReadBarrier",
	}
	CmdType_value = map[string]int32{
		"Invalid":     0,
		"Put":         3,
		"Delete":      4,
		"ReadBarrier": 5,
	}
)

func (x CmdType) Enum() *CmdType {
	p := new(CmdType)
	*p = x
	return p
}

func (x CmdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdType) Descriptor() protoreflect.EnumDescriptor {
	return file_raft_cmdpb_proto_enumTypes[0].Descriptor()
}

func (CmdType) Type() protoreflect.EnumType {
	return &file_raft_cmdpb_proto_enumTypes[0]
}

func (x CmdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdType.Descriptor instead.
func (CmdType) EnumDescriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{0}
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cf            string                 `protobuf:"bytes,1,opt,name=cf,proto3" json:"cf,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_raft_cmdpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cf            string                 `protobuf:"bytes,1,opt,name=cf,proto3" json:"cf,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_raft_cmdpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteRequest) GetCf() string {
	if x != nil {
		return x.Cf
	}
	return ""
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdType       CmdType                `protobuf:"varint,1,opt,name=cmd_type,json=cmdType,proto3,enum=raft_cmdpb.CmdType" json:"cmd_type,omitempty"`
	Put           *PutRequest            `protobuf:"bytes,4,opt,name=put,proto3" json:"put,omitempty"`
	Delete        *DeleteRequest         `protobuf:"bytes,5,opt,name=delete,proto3" json:"delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_raft_cmdpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetCmdType() CmdType {
	if x != nil {
		return x.CmdType
	}
	return CmdType_Invalid
}

func (x *Request) GetPut() *PutRequest {
	if x != nil {
		return x.Put
	}
	return nil
}

func (x *Request) GetDelete() *DeleteRequest {
	if x != nil {
		return x.Delete
	}
	return nil
}

type RaftCmdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*Request             `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftCmdRequest) Reset() {
	*x = RaftCmdRequest{}
	mi := &file_raft_cmdpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftCmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftCmdRequest) ProtoMessage() {}

func (x *RaftCmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_cmdpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftCmdRequest.ProtoReflect.Descriptor instead.
func (*RaftCmdRequest) Descriptor() ([]byte, []int) {
	return file_raft_cmdpb_proto_rawDescGZIP(), []int{3}
}

func (x *RaftCmdRequest) GetRequests() []*Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

var File_raft_cmdpb_proto protoreflect.FileDescriptor

const file_raft_cmdpb_proto_rawDesc = "" +
	"\n" +
	"\x10raft_cmdpb.proto\x12\n" +
	"raft_cmdpb\"D\n" +
	"\n" +
	"PutRequest\x12\x0e\n" +
	"\x02cf\x18\x01 \x01(\tR\x02cf\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"1\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02cf\x18\x01 \x01(\tR\x02cf\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"\xb3\x01\n" +
	"\aRequest\x12.\n" +
	"\bcmd_type\x18\x01 \x01(\x0e2\x13.raft_cmdpb.CmdTypeR\acmdType\x12(\n" +
	"\x03put\x18\x04 \x01(\v2\x16.raft_cmdpb.PutRequestR\x03put\x121\n" +
	"\x06delete\x18\x05 \x01(\v2\x19.raft_cmdpb.DeleteRequestR\x06deleteJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x06\x10\aR\x03getR\x04snap\"d\n" +
	"\x0eRaftCmdRequest\x12/\n" +
	"\brequests\x18\x02 \x03(\v2\x13.raft_cmdpb.RequestR\brequestsJ\x04\b\x01\x10\x02J\x04\b\x03\x10\x04R\x06headerR\radmin_request*G\n" +
	"\aCmdType\x12\v\n" +
	"\aInvalid\x10\x00\x12\a\n" +
	"\x03Put\x10\x03\x12\n" +
	"\n" +
	"\x06Delete\x10\x04\x12\x0f\n" +
	"\vReadBarrier\x10\x05\"\x04\b\x01\x10\x01*\x03GetB:Z8github.com/Aetherance/kv/proto/pkg/raft_cmdpb;raft_cmdpbb\x06proto3"

var (
	file_raft_cmdpb_proto_rawDescOnce sync.Once
	file_raft_cmdpb_proto_rawDescData []byte
)

func file_raft_cmdpb_proto_rawDescGZIP() []byte {
	file_raft_cmdpb_proto_rawDescOnce.Do(func() {
		file_raft_cmdpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raft_cmdpb_proto_rawDesc), len(file_raft_cmdpb_proto_rawDesc)))
	})
	return file_raft_cmdpb_proto_rawDescData
}

var file_raft_cmdpb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_raft_cmdpb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_raft_cmdpb_proto_goTypes = []any{
	(CmdType)(0),           // 0: raft_cmdpb.CmdType
	(*PutRequest)(nil),     // 1: raft_cmdpb.PutRequest
	(*DeleteRequest)(nil),  // 2: raft_cmdpb.DeleteRequest
	(*Request)(nil),        // 3: raft_cmdpb.Request
	(*RaftCmdRequest)(nil), // 4: raft_cmdpb.RaftCmdRequest
}
var file_raft_cmdpb_proto_depIdxs = []int32{
	0, // 0: raft_cmdpb.Request.cmd_type:type_name -> raft_cmdpb.CmdType
	1, // 1: raft_cmdpb.Request.put:type_name -> raft_cmdpb.PutRequest
	2, // 2: raft_cmdpb.Request.delete:type_name -> raft_cmdpb.DeleteRequest
	3, // 3: raft_cmdpb.RaftCmdRequest.requests:type_name -> raft_cmdpb.Request
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_raft_cmdpb_proto_init() }
func file_raft_cmdpb_proto_init() {
	if File_raft_cmdpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raft_cmdpb_proto_rawDesc), len(file_raft_cmdpb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_raft_cmdpb_proto_goTypes,
		DependencyIndexes: file_raft_cmdpb_proto_depIdxs,
		EnumInfos:         file_raft_cmdpb_proto_enumTypes,
		MessageInfos:      file_raft_cmdpb_proto_msgTypes,
	}.Build()
	File_raft_cmdpb_proto = out.File
	file_raft_cmdpb_proto_goTypes = nil
	file_raft_cmdpb_proto_depIdxs = nil
}
