// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: raft_serverpb.proto

package raft_serverpb

import (
	raftpb "github.com/Aetherance/kv/proto/pkg/raftpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaftMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *raftpb.Message        `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessage) Reset() {
	*x = RaftMessage{}
	mi := &file_raft_serverpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessage) ProtoMessage() {}

func (x *RaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_raft_serverpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessage.ProtoReflect.Descriptor instead.
func (*RaftMessage) Descriptor() ([]byte, []int) {
	return file_raft_serverpb_proto_rawDescGZIP(), []int{0}
}

func (x *RaftMessage) GetMessage() *raftpb.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_raft_serverpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_raft_serverpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_raft_serverpb_proto_rawDescGZIP(), []int{1}
}

func (x *KeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RaftSnapshotData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*KeyValue            `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftSnapshotData) Reset() {
	*x = RaftSnapshotData{}
	mi := &file_raft_serverpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftSnapshotData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftSnapshotData) ProtoMessage() {}

func (x *RaftSnapshotData) ProtoReflect() protoreflect.Message {
	mi := &file_raft_serverpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftSnapshotData.ProtoReflect.Descriptor instead.
func (*RaftSnapshotData) Descriptor() ([]byte, []int) {
	return file_raft_serverpb_proto_rawDescGZIP(), []int{2}
}

func (x *RaftSnapshotData) GetData() []*KeyValue {
	if x != nil {
		return x.Data
	}
	return nil
}

type Done struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Done) Reset() {
	*x = Done{}
	mi := &file_raft_serverpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_raft_serverpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_raft_serverpb_proto_rawDescGZIP(), []int{3}
}

var File_raft_serverpb_proto protoreflect.FileDescriptor

const file_raft_serverpb_proto_rawDesc = "" +
	"\n" +
	"\x13raft_serverpb.proto\x12\rraft_serverpb\x1a\fraftpb.proto\"\xb1\x01\n" +
	"\vRaftMessage\x12)\n" +
	"\amessage\x18\x04 \x01(\v2\x0f.raftpb.MessageR\amessageJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\a\x10\bJ\x04\b\b\x10\tR\tregion_idR\tfrom_peerR\ato_peerR\fregion_epochR\fis_tombstoneR\tstart_keyR\aend_key\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"j\n" +
	"\x10RaftSnapshotData\x12+\n" +
	"\x04data\x18\x03 \x03(\v2\x17.raft_serverpb.KeyValueR\x04dataJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x05\x10\x06R\x06regionR\tfile_sizeR\x04meta\"\x06\n" +
	"\x04Done2J\n" +
	"\vRaftService\x12;\n" +
	"\x04Raft\x12\x1a.raft_serverpb.RaftMessage\x1a\x13.raft_serverpb.Done\"\x00(\x01B@Z>github.com/Aetherance/kv/proto/pkg/raft_serverpb;raft_serverpbb\x06proto3"

var (
	file_raft_serverpb_proto_rawDescOnce sync.Once
	file_raft_serverpb_proto_rawDescData []byte
)

func file_raft_serverpb_proto_rawDescGZIP() []byte {
	file_raft_serverpb_proto_rawDescOnce.Do(func() {
		file_raft_serverpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raft_serverpb_proto_rawDesc), len(file_raft_serverpb_proto_rawDesc)))
	})
	return file_raft_serverpb_proto_rawDescData
}

var file_raft_serverpb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_raft_serverpb_proto_goTypes = []any{
	(*RaftMessage)(nil),      // 0: raft_serverpb.RaftMessage
	(*KeyValue)(nil),         // 1: raft_serverpb.KeyValue
	(*RaftSnapshotData)(nil), // 2: raft_serverpb.RaftSnapshotData
	(*Done)(nil),             // 3: raft_serverpb.Done
	(*raftpb.Message)(nil),   // 4: raftpb.Message
}
var file_raft_serverpb_proto_depIdxs = []int32{
	4, // 0: raft_serverpb.RaftMessage.message:type_name -> raftpb.Message
	1, // 1: raft_serverpb.RaftSnapshotData.data:type_name -> raft_serverpb.KeyValue
	0, // 2: raft_serverpb.RaftService.Raft:input_type -> raft_serverpb.RaftMessage
	3, // 3: raft_serverpb.RaftService.Raft:output_type -> raft_serverpb.Done
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_raft_serverpb_proto_init() }
func file_raft_serverpb_proto_init() {
	if File_raft_serverpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raft_serverpb_proto_rawDesc), len(file_raft_serverpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raft_serverpb_proto_goTypes,
		DependencyIndexes: file_raft_serverpb_proto_depIdxs,
		MessageInfos:      file_raft_serverpb_proto_msgTypes,
	}.Build()
	File_raft_serverpb_proto = out.File
	file_raft_serverpb_proto_goTypes = nil
	file_raft_serverpb_proto_depIdxs = nil
}
