// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: kvpb.proto

package kvpb

import (
	context "context"
	kvrpcpb "github.com/Aetherance/kv/proto/pkg/kvrpcpb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Kv_KvGet_FullMethodName    = "/kvpb.Kv/KvGet"
	Kv_KvPut_FullMethodName    = "/kvpb.Kv/KvPut"
	Kv_KvDelete_FullMethodName = "/kvpb.Kv/KvDelete"
	Kv_KvScan_FullMethodName   = "/kvpb.Kv/KvScan"
)

// KvClient is the client API for Kv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KvClient interface {
	KvGet(ctx context.Context, in *kvrpcpb.KvGetRequest, opts ...grpc.CallOption) (*kvrpcpb.KvGetResponse, error)
	KvPut(ctx context.Context, in *kvrpcpb.KvPutRequest, opts ...grpc.CallOption) (*kvrpcpb.KvPutResponse, error)
	KvDelete(ctx context.Context, in *kvrpcpb.KvDeleteRequest, opts ...grpc.CallOption) (*kvrpcpb.KvDeleteResponse, error)
	KvScan(ctx context.Context, in *kvrpcpb.KvScanRequest, opts ...grpc.CallOption) (*kvrpcpb.KvScanResponse, error)
}

type kvClient struct {
	cc grpc.ClientConnInterface
}

func NewKvClient(cc grpc.ClientConnInterface) KvClient {
	return &kvClient{cc}
}

func (c *kvClient) KvGet(ctx context.Context, in *kvrpcpb.KvGetRequest, opts ...grpc.CallOption) (*kvrpcpb.KvGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(kvrpcpb.KvGetResponse)
	err := c.cc.Invoke(ctx, Kv_KvGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvClient) KvPut(ctx context.Context, in *kvrpcpb.KvPutRequest, opts ...grpc.CallOption) (*kvrpcpb.KvPutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(kvrpcpb.KvPutResponse)
	err := c.cc.Invoke(ctx, Kv_KvPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvClient) KvDelete(ctx context.Context, in *kvrpcpb.KvDeleteRequest, opts ...grpc.CallOption) (*kvrpcpb.KvDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(kvrpcpb.KvDeleteResponse)
	err := c.cc.Invoke(ctx, Kv_KvDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvClient) KvScan(ctx context.Context, in *kvrpcpb.KvScanRequest, opts ...grpc.CallOption) (*kvrpcpb.KvScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(kvrpcpb.KvScanResponse)
	err := c.cc.Invoke(ctx, Kv_KvScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KvServer is the server API for Kv service.
// All implementations must embed UnimplementedKvServer
// for forward compatibility.
type KvServer interface {
	KvGet(context.Context, *kvrpcpb.KvGetRequest) (*kvrpcpb.KvGetResponse, error)
	KvPut(context.Context, *kvrpcpb.KvPutRequest) (*kvrpcpb.KvPutResponse, error)
	KvDelete(context.Context, *kvrpcpb.KvDeleteRequest) (*kvrpcpb.KvDeleteResponse, error)
	KvScan(context.Context, *kvrpcpb.KvScanRequest) (*kvrpcpb.KvScanResponse, error)
	mustEmbedUnimplementedKvServer()
}

// UnimplementedKvServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKvServer struct{}

func (UnimplementedKvServer) KvGet(context.Context, *kvrpcpb.KvGetRequest) (*kvrpcpb.KvGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvGet not implemented")
}
func (UnimplementedKvServer) KvPut(context.Context, *kvrpcpb.KvPutRequest) (*kvrpcpb.KvPutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvPut not implemented")
}
func (UnimplementedKvServer) KvDelete(context.Context, *kvrpcpb.KvDeleteRequest) (*kvrpcpb.KvDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvDelete not implemented")
}
func (UnimplementedKvServer) KvScan(context.Context, *kvrpcpb.KvScanRequest) (*kvrpcpb.KvScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KvScan not implemented")
}
func (UnimplementedKvServer) mustEmbedUnimplementedKvServer() {}
func (UnimplementedKvServer) testEmbeddedByValue()            {}

// UnsafeKvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KvServer will
// result in compilation errors.
type UnsafeKvServer interface {
	mustEmbedUnimplementedKvServer()
}

func RegisterKvServer(s grpc.ServiceRegistrar, srv KvServer) {
	// If the following call panics, it indicates UnimplementedKvServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Kv_ServiceDesc, srv)
}

func _Kv_KvGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(kvrpcpb.KvGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).KvGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kv_KvGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).KvGet(ctx, req.(*kvrpcpb.KvGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kv_KvPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(kvrpcpb.KvPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).KvPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kv_KvPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).KvPut(ctx, req.(*kvrpcpb.KvPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kv_KvDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(kvrpcpb.KvDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).KvDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kv_KvDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).KvDelete(ctx, req.(*kvrpcpb.KvDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kv_KvScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(kvrpcpb.KvScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServer).KvScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kv_KvScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServer).KvScan(ctx, req.(*kvrpcpb.KvScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Kv_ServiceDesc is the grpc.ServiceDesc for Kv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kvpb.Kv",
	HandlerType: (*KvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KvGet",
			Handler:    _Kv_KvGet_Handler,
		},
		{
			MethodName: "KvPut",
			Handler:    _Kv_KvPut_Handler,
		},
		{
			MethodName: "KvDelete",
			Handler:    _Kv_KvDelete_Handler,
		},
		{
			MethodName: "KvScan",
			Handler:    _Kv_KvScan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kvpb.proto",
}
