// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: kvpb.proto

package kvpb

import (
	kvrpcpb "github.com/Aetherance/kv/proto/pkg/kvrpcpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_kvpb_proto protoreflect.FileDescriptor

const file_kvpb_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"kvpb.proto\x12\x04kvpb\x1a\rkvrpcpb.proto2\xf8\x01\n" +
	"\x02Kv\x128\n" +
	"\x05KvGet\x12\x15.kvrpcpb.KvGetRequest\x1a\x16.kvrpcpb.KvGetResponse\"\x00\x128\n" +
	"\x05KvPut\x12\x15.kvrpcpb.KvPutRequest\x1a\x16.kvrpcpb.KvPutResponse\"\x00\x12A\n" +
	"\bKvDelete\x12\x18.kvrpcpb.KvDeleteRequest\x1a\x19.kvrpcpb.KvDeleteResponse\"\x00\x12;\n" +
	"\x06KvScan\x12\x16.kvrpcpb.KvScanRequest\x1a\x17.kvrpcpb.KvScanResponse\"\x00B.Z,github.com/Aetherance/kv/proto/pkg/kvpb;kvpbb\x06proto3"

var file_kvpb_proto_goTypes = []any{
	(*kvrpcpb.KvGetRequest)(nil),     // 0: kvrpcpb.KvGetRequest
	(*kvrpcpb.KvPutRequest)(nil),     // 1: kvrpcpb.KvPutRequest
	(*kvrpcpb.KvDeleteRequest)(nil),  // 2: kvrpcpb.KvDeleteRequest
	(*kvrpcpb.KvScanRequest)(nil),    // 3: kvrpcpb.KvScanRequest
	(*kvrpcpb.KvGetResponse)(nil),    // 4: kvrpcpb.KvGetResponse
	(*kvrpcpb.KvPutResponse)(nil),    // 5: kvrpcpb.KvPutResponse
	(*kvrpcpb.KvDeleteResponse)(nil), // 6: kvrpcpb.KvDeleteResponse
	(*kvrpcpb.KvScanResponse)(nil),   // 7: kvrpcpb.KvScanResponse
}
var file_kvpb_proto_depIdxs = []int32{
	0, // 0: kvpb.Kv.KvGet:input_type -> kvrpcpb.KvGetRequest
	1, // 1: kvpb.Kv.KvPut:input_type -> kvrpcpb.KvPutRequest
	2, // 2: kvpb.Kv.KvDelete:input_type -> kvrpcpb.KvDeleteRequest
	3, // 3: kvpb.Kv.KvScan:input_type -> kvrpcpb.KvScanRequest
	4, // 4: kvpb.Kv.KvGet:output_type -> kvrpcpb.KvGetResponse
	5, // 5: kvpb.Kv.KvPut:output_type -> kvrpcpb.KvPutResponse
	6, // 6: kvpb.Kv.KvDelete:output_type -> kvrpcpb.KvDeleteResponse
	7, // 7: kvpb.Kv.KvScan:output_type -> kvrpcpb.KvScanResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kvpb_proto_init() }
func file_kvpb_proto_init() {
	if File_kvpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kvpb_proto_rawDesc), len(file_kvpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kvpb_proto_goTypes,
		DependencyIndexes: file_kvpb_proto_depIdxs,
	}.Build()
	File_kvpb_proto = out.File
	file_kvpb_proto_goTypes = nil
	file_kvpb_proto_depIdxs = nil
}
