syntax = "proto3";
package errorpb;

import "metapb.proto";

option go_package = "github.com/Aetherance/kv/proto/pkg/errorpb;errorpb";

message NotLeader {
    uint64 region_id = 1;
    metapb.Peer leader = 2;
}

message RegionNotFound {
    uint64 region_id = 1;
}

message EpochNotMatch {
    repeated metapb.Region current_regions = 1;
}

message StaleCommand {
}

message Error {
    reserved 4, 8;
    reserved "stale_epoch", "key_not_in_region", "store_not_match";

    string message = 1;
    NotLeader not_leader = 2;
    RegionNotFound region_not_found = 3;
    EpochNotMatch epoch_not_match = 5;
    StaleCommand stale_command = 7;
}
