syntax = "proto3";

package kvrpcpb;

option go_package = "github.com/Aetherance/kv/proto/pkg/kvrpcpb;kvrpcpb";

message KvGetRequest {
    reserved 1;
    reserved "context";

    string cf = 2;
    bytes key = 3;
}

message KvGetResponse {
    reserved 1;
    reserved "error";

    bytes value = 2;
    bool not_found = 3;
}

message KvPutRequest {
    reserved 1;
    reserved "context";

    string cf = 2;
    bytes key = 3;
    bytes value = 4;
}

message KvPutResponse {
    reserved 1;
    reserved "error";
}

message KvDeleteRequest {
    reserved 1;
    reserved "context";

    string cf = 2;
    bytes key = 3;
}

message KvDeleteResponse {
    reserved 1;
    reserved "error";
}

message KvScanRequest {
    reserved 1;
    reserved "context";

    string cf = 2;
    bytes start_key = 3;
    uint32 limit = 4;
}

message KvScanResponse {
    reserved 1;
    reserved "error";

    repeated KvPair kvs = 2;
}

message KvPair {
    reserved 1;
    reserved "error";

    bytes key = 2;
    bytes value = 3;
}
