syntax = "proto3";
package metapb;

option go_package = "github.com/Aetherance/kv/proto/pkg/metapb;metapb";

message Store {
    reserved 2, 3;
    reserved "address", "state";

    uint64 id = 1;
}

message RegionEpoch {
    // Conf change version, auto increment when add or remove peer
    uint64 conf_ver = 1;
    // Region version, auto increment when split or merge
    uint64 version = 2;
}

message Region {
    uint64 id = 1;
    // Region key range [start_key, end_key).
    bytes start_key = 2;
    bytes end_key = 3;
    RegionEpoch region_epoch = 4;
    repeated Peer peers = 5;
}

message Peer {
    uint64 id = 1;
    uint64 store_id = 2;
}
