syntax = "proto3";
package raft_serverpb;

import "raftpb.proto";
import "clusterpb.proto";

option go_package = "github.com/Aetherance/kv/proto/pkg/raft_serverpb;raft_serverpb";

message KeyValue {
    bytes key = 1;
    bytes value = 2;
}

message RaftSnapshotData {
    reserved 1, 2, 5;
    reserved "region", "file_size", "meta";

    repeated KeyValue data = 3;
    clusterpb.ClusterMetadata cluster = 4;
}

message Done {}

service RaftService {
    rpc Raft(stream raftpb.Message) returns (Done) {}
}
