syntax = "proto3";
package raft_cmdpb;

option go_package = "github.com/Aetherance/kv/proto/pkg/raft_cmdpb;raft_cmdpb";

message PutRequest {
    string cf = 1;
    bytes key = 2;
    bytes value = 3;
}

message DeleteRequest {
    string cf = 1;
    bytes key = 2;
}

enum CmdType {
    reserved 1;
    reserved "Get";

    Invalid = 0;
    Put = 3;
    Delete = 4;
    ReadBarrier = 5;
}

message Request {
    reserved 2, 3, 6;
    reserved "get", "snap";

    CmdType cmd_type = 1;
    PutRequest put = 4;
    DeleteRequest delete = 5;
}

message RaftCmdRequest {
    reserved 1, 3;
    reserved "header", "admin_request";

    repeated Request requests = 2;
}
