// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: errorpb.proto

package errorpb

import (
	metapb "github.com/Aetherance/kv/proto/pkg/metapb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotLeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Leader        *metapb.Peer           `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotLeader) Reset() {
	*x = NotLeader{}
	mi := &file_errorpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotLeader) ProtoMessage() {}

func (x *NotLeader) ProtoReflect() protoreflect.Message {
	mi := &file_errorpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotLeader.ProtoReflect.Descriptor instead.
func (*NotLeader) Descriptor() ([]byte, []int) {
	return file_errorpb_proto_rawDescGZIP(), []int{0}
}

func (x *NotLeader) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *NotLeader) GetLeader() *metapb.Peer {
	if x != nil {
		return x.Leader
	}
	return nil
}

type RegionNotFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionNotFound) Reset() {
	*x = RegionNotFound{}
	mi := &file_errorpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionNotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionNotFound) ProtoMessage() {}

func (x *RegionNotFound) ProtoReflect() protoreflect.Message {
	mi := &file_errorpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionNotFound.ProtoReflect.Descriptor instead.
func (*RegionNotFound) Descriptor() ([]byte, []int) {
	return file_errorpb_proto_rawDescGZIP(), []int{1}
}

func (x *RegionNotFound) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

type EpochNotMatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentRegions []*metapb.Region       `protobuf:"bytes,1,rep,name=current_regions,json=currentRegions,proto3" json:"current_regions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EpochNotMatch) Reset() {
	*x = EpochNotMatch{}
	mi := &file_errorpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochNotMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochNotMatch) ProtoMessage() {}

func (x *EpochNotMatch) ProtoReflect() protoreflect.Message {
	mi := &file_errorpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochNotMatch.ProtoReflect.Descriptor instead.
func (*EpochNotMatch) Descriptor() ([]byte, []int) {
	return file_errorpb_proto_rawDescGZIP(), []int{2}
}

func (x *EpochNotMatch) GetCurrentRegions() []*metapb.Region {
	if x != nil {
		return x.CurrentRegions
	}
	return nil
}

type StaleCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaleCommand) Reset() {
	*x = StaleCommand{}
	mi := &file_errorpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaleCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaleCommand) ProtoMessage() {}

func (x *StaleCommand) ProtoReflect() protoreflect.Message {
	mi := &file_errorpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaleCommand.ProtoReflect.Descriptor instead.
func (*StaleCommand) Descriptor() ([]byte, []int) {
	return file_errorpb_proto_rawDescGZIP(), []int{3}
}

type Error struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	NotLeader      *NotLeader             `protobuf:"bytes,2,opt,name=not_leader,json=notLeader,proto3" json:"not_leader,omitempty"`
	RegionNotFound *RegionNotFound        `protobuf:"bytes,3,opt,name=region_not_found,json=regionNotFound,proto3" json:"region_not_found,omitempty"`
	EpochNotMatch  *EpochNotMatch         `protobuf:"bytes,5,opt,name=epoch_not_match,json=epochNotMatch,proto3" json:"epoch_not_match,omitempty"`
	StaleCommand   *StaleCommand          `protobuf:"bytes,7,opt,name=stale_command,json=staleCommand,proto3" json:"stale_command,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_errorpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_errorpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_errorpb_proto_rawDescGZIP(), []int{4}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetNotLeader() *NotLeader {
	if x != nil {
		return x.NotLeader
	}
	return nil
}

func (x *Error) GetRegionNotFound() *RegionNotFound {
	if x != nil {
		return x.RegionNotFound
	}
	return nil
}

func (x *Error) GetEpochNotMatch() *EpochNotMatch {
	if x != nil {
		return x.EpochNotMatch
	}
	return nil
}

func (x *Error) GetStaleCommand() *StaleCommand {
	if x != nil {
		return x.StaleCommand
	}
	return nil
}

var File_errorpb_proto protoreflect.FileDescriptor

const file_errorpb_proto_rawDesc = "" +
	"\n" +
	"\rerrorpb.proto\x12\aerrorpb\x1a\fmetapb.proto\"N\n" +
	"\tNotLeader\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x12$\n" +
	"\x06leader\x18\x02 \x01(\v2\f.metapb.PeerR\x06leader\"-\n" +
	"\x0eRegionNotFound\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\"H\n" +
	"\rEpochNotMatch\x127\n" +
	"\x0fcurrent_regions\x18\x01 \x03(\v2\x0e.metapb.RegionR\x0ecurrentRegions\"\x0e\n" +
	"\fStaleCommand\"\xd0\x02\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x121\n" +
	"\n" +
	"not_leader\x18\x02 \x01(\v2\x12.errorpb.NotLeaderR\tnotLeader\x12A\n" +
	"\x10region_not_found\x18\x03 \x01(\v2\x17.errorpb.RegionNotFoundR\x0eregionNotFound\x12>\n" +
	"\x0fepoch_not_match\x18\x05 \x01(\v2\x16.errorpb.EpochNotMatchR\repochNotMatch\x12:\n" +
	"\rstale_command\x18\a \x01(\v2\x15.errorpb.StaleCommandR\fstaleCommandJ\x04\b\x04\x10\x05J\x04\b\b\x10\tR\vstale_epochR\x11key_not_in_regionR\x0fstore_not_matchB4Z2github.com/Aetherance/kv/proto/pkg/errorpb;errorpbb\x06proto3"

var (
	file_errorpb_proto_rawDescOnce sync.Once
	file_errorpb_proto_rawDescData []byte
)

func file_errorpb_proto_rawDescGZIP() []byte {
	file_errorpb_proto_rawDescOnce.Do(func() {
		file_errorpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errorpb_proto_rawDesc), len(file_errorpb_proto_rawDesc)))
	})
	return file_errorpb_proto_rawDescData
}

var file_errorpb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_errorpb_proto_goTypes = []any{
	(*NotLeader)(nil),      // 0: errorpb.NotLeader
	(*RegionNotFound)(nil), // 1: errorpb.RegionNotFound
	(*EpochNotMatch)(nil),  // 2: errorpb.EpochNotMatch
	(*StaleCommand)(nil),   // 3: errorpb.StaleCommand
	(*Error)(nil),          // 4: errorpb.Error
	(*metapb.Peer)(nil),    // 5: metapb.Peer
	(*metapb.Region)(nil),  // 6: metapb.Region
}
var file_errorpb_proto_depIdxs = []int32{
	5, // 0: errorpb.NotLeader.leader:type_name -> metapb.Peer
	6, // 1: errorpb.EpochNotMatch.current_regions:type_name -> metapb.Region
	0, // 2: errorpb.Error.not_leader:type_name -> errorpb.NotLeader
	1, // 3: errorpb.Error.region_not_found:type_name -> errorpb.RegionNotFound
	2, // 4: errorpb.Error.epoch_not_match:type_name -> errorpb.EpochNotMatch
	3, // 5: errorpb.Error.stale_command:type_name -> errorpb.StaleCommand
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_errorpb_proto_init() }
func file_errorpb_proto_init() {
	if File_errorpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errorpb_proto_rawDesc), len(file_errorpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errorpb_proto_goTypes,
		DependencyIndexes: file_errorpb_proto_depIdxs,
		MessageInfos:      file_errorpb_proto_msgTypes,
	}.Build()
	File_errorpb_proto = out.File
	file_errorpb_proto_goTypes = nil
	file_errorpb_proto_depIdxs = nil
}
