// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: errorpb.proto

package errorpb

import (
	metapb "github.com/Aetherance/kv/proto/pkg/metapb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotLeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Leader        *metapb.Peer           `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotLeader) Reset() {
	*x = NotLeader{}
	mi := &file_errorpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotLeader) ProtoMessage() {}

func (x *NotLeader) ProtoReflect() protoreflect.Message {
	mi := &file_errorpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotLeader.ProtoReflect.Descriptor instead.
func (*NotLeader) Descriptor() ([]byte, []int) {
	return file_errorpb_proto_rawDescGZIP(), []int{0}
}

func (x *NotLeader) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *NotLeader) GetLeader() *metapb.Peer {
	if x != nil {
		return x.Leader
	}
	return nil
}

type StoreNotMatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestStoreId uint64                 `protobuf:"varint,1,opt,name=request_store_id,json=requestStoreId,proto3" json:"request_store_id,omitempty"`
	ActualStoreId  uint64                 `protobuf:"varint,2,opt,name=actual_store_id,json=actualStoreId,proto3" json:"actual_store_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoreNotMatch) Reset() {
	*x = StoreNotMatch{}
	mi := &file_errorpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreNotMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreNotMatch) ProtoMessage() {}

func (x *StoreNotMatch) ProtoReflect() protoreflect.Message {
	mi := &file_errorpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreNotMatch.ProtoReflect.Descriptor instead.
func (*StoreNotMatch) Descriptor() ([]byte, []int) {
	return file_errorpb_proto_rawDescGZIP(), []int{1}
}

func (x *StoreNotMatch) GetRequestStoreId() uint64 {
	if x != nil {
		return x.RequestStoreId
	}
	return 0
}

func (x *StoreNotMatch) GetActualStoreId() uint64 {
	if x != nil {
		return x.ActualStoreId
	}
	return 0
}

type RegionNotFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegionId      uint64                 `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionNotFound) Reset() {
	*x = RegionNotFound{}
	mi := &file_errorpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionNotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionNotFound) ProtoMessage() {}

func (x *RegionNotFound) ProtoReflect() protoreflect.Message {
	mi := &file_errorpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionNotFound.ProtoReflect.Descriptor instead.
func (*RegionNotFound) Descriptor() ([]byte, []int) {
	return file_errorpb_proto_rawDescGZIP(), []int{2}
}

func (x *RegionNotFound) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

type KeyNotInRegion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RegionId      uint64                 `protobuf:"varint,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	StartKey      []byte                 `protobuf:"bytes,3,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey        []byte                 `protobuf:"bytes,4,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyNotInRegion) Reset() {
	*x = KeyNotInRegion{}
	mi := &file_errorpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyNotInRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyNotInRegion) ProtoMessage() {}

func (x *KeyNotInRegion) ProtoReflect() protoreflect.Message {
	mi := &file_errorpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyNotInRegion.ProtoReflect.Descriptor instead.
func (*KeyNotInRegion) Descriptor() ([]byte, []int) {
	return file_errorpb_proto_rawDescGZIP(), []int{3}
}

func (x *KeyNotInRegion) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyNotInRegion) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *KeyNotInRegion) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *KeyNotInRegion) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

type EpochNotMatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentRegions []*metapb.Region       `protobuf:"bytes,1,rep,name=current_regions,json=currentRegions,proto3" json:"current_regions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EpochNotMatch) Reset() {
	*x = EpochNotMatch{}
	mi := &file_errorpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochNotMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochNotMatch) ProtoMessage() {}

func (x *EpochNotMatch) ProtoReflect() protoreflect.Message {
	mi := &file_errorpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochNotMatch.ProtoReflect.Descriptor instead.
func (*EpochNotMatch) Descriptor() ([]byte, []int) {
	return file_errorpb_proto_rawDescGZIP(), []int{4}
}

func (x *EpochNotMatch) GetCurrentRegions() []*metapb.Region {
	if x != nil {
		return x.CurrentRegions
	}
	return nil
}

type StaleCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaleCommand) Reset() {
	*x = StaleCommand{}
	mi := &file_errorpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaleCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaleCommand) ProtoMessage() {}

func (x *StaleCommand) ProtoReflect() protoreflect.Message {
	mi := &file_errorpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaleCommand.ProtoReflect.Descriptor instead.
func (*StaleCommand) Descriptor() ([]byte, []int) {
	return file_errorpb_proto_rawDescGZIP(), []int{5}
}

type Error struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Message        string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	NotLeader      *NotLeader             `protobuf:"bytes,2,opt,name=not_leader,json=notLeader,proto3" json:"not_leader,omitempty"`
	RegionNotFound *RegionNotFound        `protobuf:"bytes,3,opt,name=region_not_found,json=regionNotFound,proto3" json:"region_not_found,omitempty"`
	KeyNotInRegion *KeyNotInRegion        `protobuf:"bytes,4,opt,name=key_not_in_region,json=keyNotInRegion,proto3" json:"key_not_in_region,omitempty"`
	EpochNotMatch  *EpochNotMatch         `protobuf:"bytes,5,opt,name=epoch_not_match,json=epochNotMatch,proto3" json:"epoch_not_match,omitempty"`
	StaleCommand   *StaleCommand          `protobuf:"bytes,7,opt,name=stale_command,json=staleCommand,proto3" json:"stale_command,omitempty"`
	StoreNotMatch  *StoreNotMatch         `protobuf:"bytes,8,opt,name=store_not_match,json=storeNotMatch,proto3" json:"store_not_match,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_errorpb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_errorpb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_errorpb_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetNotLeader() *NotLeader {
	if x != nil {
		return x.NotLeader
	}
	return nil
}

func (x *Error) GetRegionNotFound() *RegionNotFound {
	if x != nil {
		return x.RegionNotFound
	}
	return nil
}

func (x *Error) GetKeyNotInRegion() *KeyNotInRegion {
	if x != nil {
		return x.KeyNotInRegion
	}
	return nil
}

func (x *Error) GetEpochNotMatch() *EpochNotMatch {
	if x != nil {
		return x.EpochNotMatch
	}
	return nil
}

func (x *Error) GetStaleCommand() *StaleCommand {
	if x != nil {
		return x.StaleCommand
	}
	return nil
}

func (x *Error) GetStoreNotMatch() *StoreNotMatch {
	if x != nil {
		return x.StoreNotMatch
	}
	return nil
}

var File_errorpb_proto protoreflect.FileDescriptor

const file_errorpb_proto_rawDesc = "" +
	"\n" +
	"\rerrorpb.proto\x12\aerrorpb\x1a\fmetapb.proto\"N\n" +
	"\tNotLeader\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\x12$\n" +
	"\x06leader\x18\x02 \x01(\v2\f.metapb.PeerR\x06leader\"a\n" +
	"\rStoreNotMatch\x12(\n" +
	"\x10request_store_id\x18\x01 \x01(\x04R\x0erequestStoreId\x12&\n" +
	"\x0factual_store_id\x18\x02 \x01(\x04R\ractualStoreId\"-\n" +
	"\x0eRegionNotFound\x12\x1b\n" +
	"\tregion_id\x18\x01 \x01(\x04R\bregionId\"u\n" +
	"\x0eKeyNotInRegion\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1b\n" +
	"\tregion_id\x18\x02 \x01(\x04R\bregionId\x12\x1b\n" +
	"\tstart_key\x18\x03 \x01(\fR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x04 \x01(\fR\x06endKey\"H\n" +
	"\rEpochNotMatch\x127\n" +
	"\x0fcurrent_regions\x18\x01 \x03(\v2\x0e.metapb.RegionR\x0ecurrentRegions\"\x0e\n" +
	"\fStaleCommand\"\xa4\x03\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x121\n" +
	"\n" +
	"not_leader\x18\x02 \x01(\v2\x12.errorpb.NotLeaderR\tnotLeader\x12A\n" +
	"\x10region_not_found\x18\x03 \x01(\v2\x17.errorpb.RegionNotFoundR\x0eregionNotFound\x12B\n" +
	"\x11key_not_in_region\x18\x04 \x01(\v2\x17.errorpb.KeyNotInRegionR\x0ekeyNotInRegion\x12>\n" +
	"\x0fepoch_not_match\x18\x05 \x01(\v2\x16.errorpb.EpochNotMatchR\repochNotMatch\x12:\n" +
	"\rstale_command\x18\a \x01(\v2\x15.errorpb.StaleCommandR\fstaleCommand\x12>\n" +
	"\x0fstore_not_match\x18\b \x01(\v2\x16.errorpb.StoreNotMatchR\rstoreNotMatchR\vstale_epochB4Z2github.com/Aetherance/kv/proto/pkg/errorpb;errorpbb\x06proto3"

var (
	file_errorpb_proto_rawDescOnce sync.Once
	file_errorpb_proto_rawDescData []byte
)

func file_errorpb_proto_rawDescGZIP() []byte {
	file_errorpb_proto_rawDescOnce.Do(func() {
		file_errorpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errorpb_proto_rawDesc), len(file_errorpb_proto_rawDesc)))
	})
	return file_errorpb_proto_rawDescData
}

var file_errorpb_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_errorpb_proto_goTypes = []any{
	(*NotLeader)(nil),      // 0: errorpb.NotLeader
	(*StoreNotMatch)(nil),  // 1: errorpb.StoreNotMatch
	(*RegionNotFound)(nil), // 2: errorpb.RegionNotFound
	(*KeyNotInRegion)(nil), // 3: errorpb.KeyNotInRegion
	(*EpochNotMatch)(nil),  // 4: errorpb.EpochNotMatch
	(*StaleCommand)(nil),   // 5: errorpb.StaleCommand
	(*Error)(nil),          // 6: errorpb.Error
	(*metapb.Peer)(nil),    // 7: metapb.Peer
	(*metapb.Region)(nil),  // 8: metapb.Region
}
var file_errorpb_proto_depIdxs = []int32{
	7, // 0: errorpb.NotLeader.leader:type_name -> metapb.Peer
	8, // 1: errorpb.EpochNotMatch.current_regions:type_name -> metapb.Region
	0, // 2: errorpb.Error.not_leader:type_name -> errorpb.NotLeader
	2, // 3: errorpb.Error.region_not_found:type_name -> errorpb.RegionNotFound
	3, // 4: errorpb.Error.key_not_in_region:type_name -> errorpb.KeyNotInRegion
	4, // 5: errorpb.Error.epoch_not_match:type_name -> errorpb.EpochNotMatch
	5, // 6: errorpb.Error.stale_command:type_name -> errorpb.StaleCommand
	1, // 7: errorpb.Error.store_not_match:type_name -> errorpb.StoreNotMatch
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_errorpb_proto_init() }
func file_errorpb_proto_init() {
	if File_errorpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errorpb_proto_rawDesc), len(file_errorpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errorpb_proto_goTypes,
		DependencyIndexes: file_errorpb_proto_depIdxs,
		MessageInfos:      file_errorpb_proto_msgTypes,
	}.Build()
	File_errorpb_proto = out.File
	file_errorpb_proto_goTypes = nil
	file_errorpb_proto_depIdxs = nil
}
