// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: clusterpb.proto

package clusterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RaftAddress   string                 `protobuf:"bytes,2,opt,name=raft_address,json=raftAddress,proto3" json:"raft_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_clusterpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Member) GetRaftAddress() string {
	if x != nil {
		return x.RaftAddress
	}
	return ""
}

// ClusterMetadata is the durable application-level membership registry. Raft
// voting roles remain authoritative in raftpb.ConfState.
type ClusterMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClusterId        uint64                 `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Members          []*Member              `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	RemovedMemberIds []uint64               `protobuf:"varint,3,rep,packed,name=removed_member_ids,json=removedMemberIds,proto3" json:"removed_member_ids,omitempty"`
	ConfRevision     uint64                 `protobuf:"varint,4,opt,name=conf_revision,json=confRevision,proto3" json:"conf_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClusterMetadata) Reset() {
	*x = ClusterMetadata{}
	mi := &file_clusterpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMetadata) ProtoMessage() {}

func (x *ClusterMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_clusterpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMetadata.ProtoReflect.Descriptor instead.
func (*ClusterMetadata) Descriptor() ([]byte, []int) {
	return file_clusterpb_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterMetadata) GetClusterId() uint64 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *ClusterMetadata) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ClusterMetadata) GetRemovedMemberIds() []uint64 {
	if x != nil {
		return x.RemovedMemberIds
	}
	return nil
}

func (x *ClusterMetadata) GetConfRevision() uint64 {
	if x != nil {
		return x.ConfRevision
	}
	return 0
}

var File_clusterpb_proto protoreflect.FileDescriptor

const file_clusterpb_proto_rawDesc = "" +
	"\n" +
	"\x0fclusterpb.proto\x12\tclusterpb\";\n" +
	"\x06Member\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\fraft_address\x18\x02 \x01(\tR\vraftAddress\"\xb0\x01\n" +
	"\x0fClusterMetadata\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\x04R\tclusterId\x12+\n" +
	"\amembers\x18\x02 \x03(\v2\x11.clusterpb.MemberR\amembers\x12,\n" +
	"\x12removed_member_ids\x18\x03 \x03(\x04R\x10removedMemberIds\x12#\n" +
	"\rconf_revision\x18\x04 \x01(\x04R\fconfRevisionB8Z6github.com/Aetherance/kv/proto/pkg/clusterpb;clusterpbb\x06proto3"

var (
	file_clusterpb_proto_rawDescOnce sync.Once
	file_clusterpb_proto_rawDescData []byte
)

func file_clusterpb_proto_rawDescGZIP() []byte {
	file_clusterpb_proto_rawDescOnce.Do(func() {
		file_clusterpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clusterpb_proto_rawDesc), len(file_clusterpb_proto_rawDesc)))
	})
	return file_clusterpb_proto_rawDescData
}

var file_clusterpb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clusterpb_proto_goTypes = []any{
	(*Member)(nil),          // 0: clusterpb.Member
	(*ClusterMetadata)(nil), // 1: clusterpb.ClusterMetadata
}
var file_clusterpb_proto_depIdxs = []int32{
	0, // 0: clusterpb.ClusterMetadata.members:type_name -> clusterpb.Member
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clusterpb_proto_init() }
func file_clusterpb_proto_init() {
	if File_clusterpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clusterpb_proto_rawDesc), len(file_clusterpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clusterpb_proto_goTypes,
		DependencyIndexes: file_clusterpb_proto_depIdxs,
		MessageInfos:      file_clusterpb_proto_msgTypes,
	}.Build()
	File_clusterpb_proto = out.File
	file_clusterpb_proto_goTypes = nil
	file_clusterpb_proto_depIdxs = nil
}
